# Generated by Django 4.0.5 on 2022-07-20 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sesija',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=100)),
                ('datum', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=50)),
                ('pozicija', models.IntegerField()),
                ('poeni', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Vest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_id', models.CharField(max_length=500)),
                ('naslov', models.CharField(max_length=500)),
                ('privju', models.CharField(max_length=1000)),
                ('url', models.CharField(max_length=200)),
                ('slika', models.CharField(max_length=500)),
                ('tekst', models.CharField(max_length=10000)),
                ('skrejp_datum', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vozac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=30)),
                ('prezime', models.CharField(max_length=30)),
                ('pozicija', models.IntegerField()),
                ('poeni', models.IntegerField()),
                ('drzava', models.CharField(max_length=80)),
                ('tim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formula_app.tim')),
            ],
        ),
        migrations.CreateModel(
            name='Trka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('race_id', models.IntegerField()),
                ('status', models.CharField(max_length=20)),
                ('ime', models.CharField(max_length=100)),
                ('drzava', models.CharField(max_length=80)),
                ('staza', models.CharField(max_length=100)),
                ('pocetok', models.CharField(max_length=20)),
                ('sesii', models.ManyToManyField(to='formula_app.sesija')),
            ],
        ),
    ]
