# Generated by Django 4.0.5 on 2022-08-07 13:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import formula_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sesija',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.IntegerField(default=0)),
                ('ime', models.TextField()),
                ('trka_ime', models.TextField()),
                ('datum', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=50)),
                ('pozicija', models.IntegerField(default=0)),
                ('poeni', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Trka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('race_id', models.IntegerField()),
                ('status', models.TextField()),
                ('ime', models.TextField()),
                ('drzava', models.TextField()),
                ('staza', models.TextField()),
                ('pocetok', models.DateField(default='2022-08-07')),
                ('kraj', models.DateField(default='2022-08-07')),
                ('staza_slika', models.TextField(default='nema')),
                ('pozadina_slika', models.TextField(default='nema')),
            ],
        ),
        migrations.CreateModel(
            name='Vest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naslov', models.CharField(max_length=500)),
                ('privju', models.CharField(max_length=1000)),
                ('url', models.CharField(max_length=500)),
                ('slika', models.CharField(max_length=500)),
                ('tekst', models.TextField()),
                ('skrejp_datum', models.DateTimeField(default=django.utils.timezone.now)),
                ('source', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Vozac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.TextField()),
                ('prezime', models.TextField()),
                ('pozicija', models.IntegerField(default=0)),
                ('poeni', models.IntegerField(default=0)),
                ('drzava', models.TextField()),
                ('slika', models.TextField(default='nema-slika')),
                ('tim', models.ForeignKey(default=formula_app.models.get_placeholder_team, on_delete=models.SET(formula_app.models.get_placeholder_team), to='formula_app.tim')),
            ],
        ),
        migrations.CreateModel(
            name='TrkaSesija',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sesija', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formula_app.sesija')),
                ('trka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formula_app.trka')),
            ],
        ),
        migrations.AddField(
            model_name='trka',
            name='sesii',
            field=models.ManyToManyField(blank=True, through='formula_app.TrkaSesija', to='formula_app.sesija'),
        ),
    ]
