# Generated by Django 4.0.5 on 2022-08-09 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formula_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trka',
            name='kraj',
            field=models.DateField(default='2022-08-09'),
        ),
        migrations.AlterField(
            model_name='trka',
            name='pocetok',
            field=models.DateField(default='2022-08-09'),
        ),
    ]
