# Generated by Django 4.0.5 on 2022-07-20 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formula_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vest',
            name='skrejp_datum',
            field=models.DateTimeField(default=None),
        ),
    ]
