# Generated by Django 4.0.5 on 2022-07-20 15:59

from django.db import migrations, models
import django.db.models.deletion
import formula_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('formula_app', '0002_alter_vest_skrejp_datum'),
    ]

    operations = [
        migrations.AddField(
            model_name='vozac',
            name='slika',
            field=models.CharField(default='nema-slika', max_length=30),
        ),
        migrations.AlterField(
            model_name='tim',
            name='poeni',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tim',
            name='pozicija',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vozac',
            name='poeni',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vozac',
            name='pozicija',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vozac',
            name='tim',
            field=models.ForeignKey(default=formula_app.models.get_placeholder_team, on_delete=django.db.models.deletion.CASCADE, to='formula_app.tim'),
        ),
    ]
