# Generated by Django 4.0.5 on 2022-07-23 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formula_app', '0003_vozac_slika_alter_tim_poeni_alter_tim_pozicija_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vest',
            name='tekst',
            field=models.TextField(),
        ),
    ]
