# Generated by Django 4.0.6 on 2022-07-23 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formula_app', '0004_alter_vest_tekst'),
    ]

    operations = [
        migrations.AddField(
            model_name='sesija',
            name='session_id',
            field=models.IntegerField(default=0),
        ),
    ]
