# Generated by Django 4.0.5 on 2022-07-24 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formula_app', '0006_poraka'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Poraka',
        ),
    ]
