# Generated by Django 4.0.5 on 2022-07-25 20:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('formula_app', '0007_delete_poraka'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vest',
            name='skrejp_datum',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='vest',
            name='url',
            field=models.CharField(max_length=500),
        ),
    ]
