# Generated by Django 4.0.5 on 2022-07-26 15:11

from django.db import migrations, models
import formula_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('formula_app', '0008_alter_vest_skrejp_datum_alter_vest_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vozac',
            name='tim',
            field=models.ForeignKey(default=formula_app.models.get_placeholder_team, on_delete=models.SET(formula_app.models.get_placeholder_team), to='formula_app.tim'),
        ),
    ]
