# Generated by Django 4.0.5 on 2022-07-26 15:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('formula_app', '0009_alter_vozac_tim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trka',
            name='pocetok',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 26, 15, 18, 7, 528747, tzinfo=utc)),
        ),
    ]
