# Generated by Django 4.0.5 on 2022-07-26 15:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('formula_app', '0011_alter_trka_pocetok'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sesija',
            name='datum',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
