# Generated by Django 4.0.5 on 2022-07-26 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formula_app', '0012_alter_sesija_datum'),
    ]

    operations = [
        migrations.AddField(
            model_name='sesija',
            name='trka_ime',
            field=models.CharField(default='temp trka ime sesija', max_length=100),
            preserve_default=False,
        ),
    ]
