# Generated by Django 4.0.5 on 2022-07-26 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formula_app', '0013_sesija_trka_ime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trka',
            name='pocetok',
            field=models.DateField(default='2022-07-26'),
        ),
    ]
