# Generated by Django 4.0.5 on 2022-07-26 15:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('formula_app', '0014_alter_trka_pocetok'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sesija',
            name='datum',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
