# Generated by Django 4.0.5 on 2022-07-26 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formula_app', '0016_trkasesija_alter_trka_sesii_trkasesija_trka'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vest',
            name='custom_id',
        ),
        migrations.AddField(
            model_name='vest',
            name='source',
            field=models.CharField(default='unknown', max_length=30),
            preserve_default=False,
        ),
    ]
