# Generated by Django 4.0.5 on 2022-07-29 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formula_app', '0017_remove_vest_custom_id_vest_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='trka',
            name='pozadina_slika',
            field=models.CharField(default='nema', max_length=30),
        ),
        migrations.AddField(
            model_name='trka',
            name='staza_slika',
            field=models.CharField(default='nema', max_length=30),
        ),
        migrations.AlterField(
            model_name='trka',
            name='pocetok',
            field=models.DateField(default='2022-07-29'),
        ),
    ]
